export const ACCORDION_REGISTER = 'ACCORDION_REGISTER';
export const ACCORDION_TOGGLE = 'ACCORDION_TOGGLE';
export const ACCORDION_DELETE = 'ACCORDION_DELETE';
export const ACCORDION_RESET = 'ACCORDION_RESET';
