export default Object.freeze({
  CONFIRMATION_DELETE_NODE: 'CONFIRMATION_DELETE_NODE',
  CONFIRMATION_DELETE_STRUCTURE: 'CONFIRMATION_DELETE_STRUCTURE',
  NODE_EDIT: 'NODE_EDIT',
  NODE_CREATE: 'NODE_CREATE',
});
